/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yuo_aircraftctrl_MyJNI */

#ifndef _Included_com_yuo_aircraftctrl_MyJNI
#define _Included_com_yuo_aircraftctrl_MyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yuo_aircraftctrl_MyJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yuo_aircraftctrl_MyJNI_sayHello
        (JNIEnv *, jclass);

/*
 * Class:     com_yuo_aircraftctrl_MyJNI
 * Method:    trainBMP
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yuo_aircraftctrl_MyJNI_trainBMP
        (JNIEnv *, jclass, jint, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_yuo_aircraftctrl_MyJNI
 * Method:    Identify
 * Signature: (Landroid/graphics/Bitmap;Ljava/lang/String;)Lcom/yuo/aircraftctrl/IdentiResult;
 */
JNIEXPORT jstring JNICALL Java_com_yuo_aircraftctrl_MyJNI_Identify
        (JNIEnv *, jclass, jbyteArray , jint, jint);

#ifdef __cplusplus
}
#endif
#endif
